version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=yourpassword

volumes:
  mongodb_data_container:
